# Generated by Django 3.0.1 on 2026-05-12 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('fuel_tag', models.CharField(default='PETROL ONLY', max_length=20)),
                ('price_12_hours', models.IntegerField()),
                ('price_24_hours', models.IntegerField()),
                ('km_limit_12h', models.IntegerField(default=150)),
                ('km_limit_24h', models.IntegerField(default=250)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=15)),
                ('pickup_date', models.DateField()),
                ('rental_mode', models.CharField(max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Car')),
            ],
        ),
    ]
